**Creating a DataFrame**

In [152]:
import numpy as np
import pandas as pd

In [153]:
# creating the data dict
data = {
    "Name":['john', 'peter', 'aman', 'lama'],
    "Age": [28,22,56,44],
    "City":["New York", "Paris", "Berlin", "London"],
    "Salary":[55000, 65000, 45000, 66000]
}

In [154]:
df = (pd.DataFrame(data))
df

    Name  Age      City  Salary
0   john   28  New York   55000
1  peter   22     Paris   65000
2   aman   56    Berlin   45000
3   lama   44    London   66000

In [155]:
# now creating a data form a list 
data_list = [
    ['john', 'peter', 'aman', 'lama'],
    [28,22,56,44],
    ["New York", "Paris", "Berlin", "London"],
    [55000, 65000, 45000, 66000]
]

In [156]:
df2 = pd.DataFrame(data_list)
df2

          0      1       2       3
0      john  peter    aman    lama
1        28     22      56      44
2  New York  Paris  Berlin  London
3     55000  65000   45000   66000

In [157]:
column = ["Name", "Age", "City", "Salary"]

In [158]:
df2 = pd.DataFrame(data_list, columns = column)
df2

       Name    Age    City  Salary
0      john  peter    aman    lama
1        28     22      56      44
2  New York  Paris  Berlin  London
3     55000  65000   45000   66000

**Selection and indexing of coulmns**

In [159]:
# Lets start with selecting a column and multiple column

df2["Name"]

0        john
1          28
2    New York
3       55000
Name: Name, dtype: object

In [160]:
#multiple column
df[["Name", "Age", "Salary"]]

    Name  Age  Salary
0   john   28   55000
1  peter   22   65000
2   aman   56   45000
3   lama   44   66000

**Creating a new column**

In [161]:
df2["Hobby"] = ["A", "B", "C", "D"]
df2

       Name    Age    City  Salary Hobby
0      john  peter    aman    lama     A
1        28     22      56      44     B
2  New York  Paris  Berlin  London     C
3     55000  65000   45000   66000     D

**Removing column**

In [162]:
# for row the axis is 0 and for column the axis in 1
df2.drop("Hobby", axis = 1, inplace=True) # and you can write inplace=True which is gonna remove your data in your ram too

In [163]:
df2

       Name    Age    City  Salary
0      john  peter    aman    lama
1        28     22      56      44
2  New York  Paris  Berlin  London
3     55000  65000   45000   66000

In [164]:
# now removing muntiple column form the table
df2.drop(["City", "Salary"], axis = 1)

       Name    Age
0      john  peter
1        28     22
2  New York  Paris
3     55000  65000

**Adding new Row**

In [165]:
df = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})

# Add a row using a list of values
df.loc[len(df)] = ['Charlie', 35]

# Alternatively, add a row using a dictionary (handles column mismatch safely)
df.loc[len(df)] = {'Name': 'Diana', 'Age': 28}

**Removing row**

In [166]:
df2.drop(1, axis = 0) # just change the axis to 0 and enter the index you want to remove

       Name    Age    City  Salary
0      john  peter    aman    lama
2  New York  Paris  Berlin  London
3     55000  65000   45000   66000

**Selecting Rows**

In [167]:
# we selec row using loc[] function with basically stands for location of the row
df2.loc[2]

Name      New York
Age          Paris
City        Berlin
Salary      London
Name: 2, dtype: object

In [168]:
df2.loc[[0,1]] #for selecting muntiple rows

   Name    Age  City Salary
0  john  peter  aman   lama
1    28     22    56     44

**How to update a perticular index in dataframe**

In [169]:
data = {
    "Name": ["Rahul", "Priya", "Aman", "Sneha"],
    "Math": [85, 90, 75, 88],
    "Science": [80, 95, 82, 91]
}

df = pd.DataFrame(data)

df.loc[2, "Math"] = 85
df

    Name  Math  Science
0  Rahul    85       80
1  Priya    90       95
2   Aman    85       82
3  Sneha    88       91

**Selecting subset of rows and columns**

In [170]:
df.loc[[0,1]][["Math","Science"]] # this selects a subset fo row and column

   Math  Science
0    85       80
1    90       95

**Conditional selecation**

In [171]:
data = {
    "Name": ["Rahul", "Priya", "Aman", "Sneha", "Ravi"],
    "Math": [85, 92, 76, 88, 65],
    "Science": [78, 89, 81, 95, 70]
}

df = pd.DataFrame(data)
df

    Name  Math  Science
0  Rahul    85       78
1  Priya    92       89
2   Aman    76       81
3  Sneha    88       95
4   Ravi    65       70

In [172]:
df["Math"] > 80 # boolian series

0     True
1     True
2    False
3     True
4    False
Name: Math, dtype: bool

In [173]:
df[df["Math"] > 80] # sutdent having more then 80 marks in maths

    Name  Math  Science
0  Rahul    85       78
1  Priya    92       89
3  Sneha    88       95

In [174]:
df[df["Math"] == 85]

    Name  Math  Science
0  Rahul    85       78

In [175]:
df[df["Name"] == "Rahul"]

    Name  Math  Science
0  Rahul    85       78

In [176]:
df[(df["Math"] > 80) & (df["Science"] > 80)]

    Name  Math  Science
1  Priya    92       89
3  Sneha    88       95

In [177]:
df[(df["Math"] > 90) | (df["Science"] > 90)] # in pandas we dont write {and}, {or} we write {&}, {|}

    Name  Math  Science
1  Priya    92       89
3  Sneha    88       95

In [178]:
# Suppose you only want the names of students who scored above 80 in Math.
df[df["Math"] > 80]["Name"]

0    Rahul
1    Priya
3    Sneha
Name: Name, dtype: str

In [179]:
# you can also write this 
df.loc[df["Math"] > 80, "Name"] # for muntiple column do this ["Name", "Math"]

0    Rahul
1    Priya
3    Sneha
Name: Name, dtype: str

In [180]:
# you can create a new column based on a condition.
df["Pass"] = df["Math"] >= 40