In [1]:
import numpy as np 
import pandas as pd

**Finding Missing Data**

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [3]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

**Finding Missing Data**

In [4]:
df.isna() #isna() is basically asking a question... "Is this value missing?"

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
#Counting Missing Values 
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [9]:
"""
But why does .sum() count missing values?
Because Python treats:
True  = 1
False = 0
"""

'\nBut why does .sum() count missing values?\nBecause Python treats:\nTrue  = 1\nFalse = 0\n'

In [11]:
df.isna().any() # Does this column contain at least ONE missing value?

A     True
B    False
C     True
D     True
dtype: bool

**Removing Missing Data**

In [14]:
df.dropna() #Very Important: dropna() doesn't change df its simpilly drop row with NA

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(inplace=True) # now this changes the df in the ram

In [19]:
df.dropna(thresh=1) # thresh= 1, Keep rows having at least 1 non-missing value.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [20]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**Filling missing data**

In [23]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [24]:
# Filling Different Columns with Different Values
values = {
    'A': 0,
    'B': 100,
    'C': 300,
    'D': 400
}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [26]:
df.fillna(df.mean()) # df.mean() calculates the average of each column.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [27]:
#df["Marks"].fillna(df["Marks"].mean())

**You may encounter this**

In [30]:
df.isnull() # check null value

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [31]:
df.notna() #checks for values that are NOT missing.

       A     B      C      D
0   True  True   True   True
1   True  True   True  False
2  False  True   True  False
3   True  True  False  False
4   True  True  False   True

             DATAFRAME
                 ↓
       Do I have missing data?
                 ↓
          df.isna().sum()
                 ↓
       How much is missing?
                 ↓
        ┌────────┴────────┐
        ↓                 ↓
    Very little       A lot / important
        ↓                 ↓
     Remove?           Fill it?
        ↓                 ↓
    dropna()       fillna(...)
                          ↓
                  ┌───────┼────────┐
                  ↓       ↓        ↓
                  0      Mean    Median
                          ↓
                        Mode