**3rd no sums found below**

In [1]:
import numpy as np 
import pandas as pd

In [2]:
patients = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5, 6],
    "Name": ["Rahul", "Anita", "Suresh", "Pooja", "Vikas", "Meena"],
    "Doctor_ID": [101, 102, 101, 103, 104, 102],
    "Age": [25, 34, np.nan, 45, 29, np.nan]
})

doctors = pd.DataFrame({
    "Doctor_ID": [101, 102, 103, 104],
    "Doctor": ["Dr. Sharma", "Dr. Mehta", "Dr. Khan", "Dr. Singh"],
    "Department": ["Cardiology", "Neurology", "Orthopedic", "Dermatology"]
})

followup = pd.DataFrame({
    "Patient_ID": [7, 8],
    "Name": ["Arjun", "Kavita"],
    "Doctor_ID": [103, 104],
    "Age": [38, 31]
})

In [6]:
pd.isnull(patients).sum()

Patient_ID    0
Name          0
Doctor_ID     0
Age           2
dtype: int64

In [11]:
m = patients["Age"].mean()

In [12]:
patients["Age"] = patients["Age"].fillna(m)

In [23]:
all_p = pd.concat([patients, followup])

In [24]:
all_p

   Patient_ID    Name  Doctor_ID    Age
0           1   Rahul        101  25.00
1           2   Anita        102  34.00
2           3  Suresh        101  33.25
3           4   Pooja        103  45.00
4           5   Vikas        104  29.00
5           6   Meena        102  33.25
0           7   Arjun        103  38.00
1           8  Kavita        104  31.00

In [26]:
all_patients = all_p.reset_index(drop=True)

In [27]:
all_patients

   Patient_ID    Name  Doctor_ID    Age
0           1   Rahul        101  25.00
1           2   Anita        102  34.00
2           3  Suresh        101  33.25
3           4   Pooja        103  45.00
4           5   Vikas        104  29.00
5           6   Meena        102  33.25
6           7   Arjun        103  38.00
7           8  Kavita        104  31.00

In [29]:
finaldf = pd.merge(all_p, doctors)

In [34]:
finaldf

   Patient_ID    Name  Doctor_ID    Age      Doctor   Department
0           1   Rahul        101  25.00  Dr. Sharma   Cardiology
1           2   Anita        102  34.00   Dr. Mehta    Neurology
2           3  Suresh        101  33.25  Dr. Sharma   Cardiology
3           4   Pooja        103  45.00    Dr. Khan   Orthopedic
4           5   Vikas        104  29.00   Dr. Singh  Dermatology
5           6   Meena        102  33.25   Dr. Mehta    Neurology
6           7   Arjun        103  38.00    Dr. Khan   Orthopedic
7           8  Kavita        104  31.00   Dr. Singh  Dermatology

In [33]:
finaldf.groupby("Doctor")["Patient_ID"].count()

Doctor
Dr. Khan      2
Dr. Mehta     2
Dr. Sharma    2
Dr. Singh     2
Name: Patient_ID, dtype: int64

In [36]:
dep = finaldf.groupby("Department")["Patient_ID"].count()

In [39]:
dep

Department
Cardiology     2
Dermatology    2
Neurology      2
Orthopedic     2
Name: Patient_ID, dtype: int64

In [38]:
dep.idxmax()

'Cardiology'

In [46]:
newdf = finaldf[["Name", "Doctor", "Department", "Age"]]

In [47]:
newdf

     Name      Doctor   Department    Age
0   Rahul  Dr. Sharma   Cardiology  25.00
1   Anita   Dr. Mehta    Neurology  34.00
2  Suresh  Dr. Sharma   Cardiology  33.25
3   Pooja    Dr. Khan   Orthopedic  45.00
4   Vikas   Dr. Singh  Dermatology  29.00
5   Meena   Dr. Mehta    Neurology  33.25
6   Arjun    Dr. Khan   Orthopedic  38.00
7  Kavita   Dr. Singh  Dermatology  31.00

**pivot_table**

In [52]:
data = {
    'Date': pd.date_range('2026-09-03', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep      Month Quarter
0  2026-09-03       A   East    371     98   John  September      Q3
1  2026-09-04       B   West    998     36   Mary  September      Q3
2  2026-09-05       C  North    926     53    Bob  September      Q3
3  2026-09-06       D  South    526     87  Alice  September      Q3
4  2026-09-07       A   East    934     64   John  September      Q3
5  2026-09-08       B   West    303     74   Mary  September      Q3
6  2026-09-09       C  North    330     49    Bob  September      Q3
7  2026-09-10       D  South    825     42  Alice  September      Q3
8  2026-09-11       A   East    190     52   John  September      Q3
9  2026-09-12       B   West    755     28   Mary  September      Q3
10 2026-09-13       C  North    626     53    Bob  September      Q3
11 2026-09-14       D  South    629     33  Alice  September      Q3
12 2026-09-15       A   East    413     95   John  September      Q3
13 2026-09-16       B   West    463     50   Mary  September      Q3
14 2026-09-17       C  North    526     66    Bob  September      Q3
15 2026-09-18       D  South    663     20  Alice  September      Q3
16 2026-09-19       A   East    196     78   John  September      Q3
17 2026-09-20       B   West    812     69   Mary  September      Q3
18 2026-09-21       C  North    236     93    Bob  September      Q3
19 2026-09-22       D  South    456     78  Alice  September      Q3

In [55]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     371.0    NaN    NaN    NaN
North      NaN    NaN  526.0    NaN
South      NaN    NaN    NaN  629.0
West       NaN  755.0    NaN    NaN

In [57]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'sum')

Product       A       B       C       D
Region
East     2104.0     NaN     NaN     NaN
North       NaN     NaN  2644.0     NaN
South       NaN     NaN     NaN  3099.0
West        NaN  3331.0     NaN     NaN

In [59]:
df.groupby(["Region", "Product"])["Sales"].sum() #That's a Series with a MultiIndex.

Region  Product
East    A          2104
North   C          2644
South   D          3099
West    B          3331
Name: Sales, dtype: int32

In [60]:
pivot2 = pd.pivot_table(
    df,
    values=["Sales", "Units"],
    index="Region",
    columns="Product"
)

In [62]:
pivot2 #This is called a MultiIndex on the columns.

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     420.8    NaN    NaN    NaN  77.4   NaN   NaN   NaN
North      NaN    NaN  528.8    NaN   NaN   NaN  62.8   NaN
South      NaN    NaN    NaN  619.8   NaN   NaN   NaN  52.0
West       NaN  666.2    NaN    NaN   NaN  51.4   NaN   NaN

In [66]:
pivot3 = pd.pivot_table(
    df,
    values=["Sales", "Units"],
    index="Region",
    columns="Product",
    aggfunc={
        "Sales": "sum",
        "Units": "sum"
    }
)

pivot3

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     2104.0     NaN     NaN     NaN  387.0    NaN    NaN    NaN
North       NaN     NaN  2644.0     NaN    NaN    NaN  314.0    NaN
South       NaN     NaN     NaN  3099.0    NaN    NaN    NaN  260.0
West        NaN  3331.0     NaN     NaN    NaN  257.0    NaN    NaN

In [69]:
pivot4 = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc=["sum", "mean", "max"]
)
pivot4 #muntiple aggrigation

            sum                           mean                         max  \
Product       A       B       C       D      A      B      C      D      A
Region
East     2104.0     NaN     NaN     NaN  420.8    NaN    NaN    NaN  934.0
North       NaN     NaN  2644.0     NaN    NaN    NaN  528.8    NaN    NaN
South       NaN     NaN     NaN  3099.0    NaN    NaN    NaN  619.8    NaN
West        NaN  3331.0     NaN     NaN    NaN  666.2    NaN    NaN    NaN


Product      B      C      D
Region
East       NaN    NaN    NaN
North      NaN  926.0    NaN
South      NaN    NaN  825.0
West     998.0    NaN    NaN

In [71]:
pivot5 = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)

pivot5 # for filling the missing value

Product     A     B     C     D
Region
East     2104     0     0     0
North       0     0  2644     0
South       0     0     0  3099
West        0  3331     0     0

In [76]:
# for getting total 

pivot6 = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

pivot6

Product     A     B     C     D    All
Region
East     2104     0     0     0   2104
North       0     0  2644     0   2644
South       0     0     0  3099   3099
West        0  3331     0     0   3331
All      2104  3331  2644  3099  11178

In [77]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [79]:
import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Male', 'Female'],
    'Time': ['Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch'],
    'Bill': [15, 28, 32, 18, 45, 12]
}
df = pd.DataFrame(data)

df

   Gender    Time  Bill
0    Male   Lunch    15
1  Female  Dinner    28
2  Female  Dinner    32
3    Male   Lunch    18
4    Male  Dinner    45
5  Female   Lunch    12

In [80]:
print(pd.crosstab(df['Gender'], df['Time']))

Time    Dinner  Lunch
Gender
Female       2      1
Male         1      2