In [25]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\test\miniconda3\envs\data_analysis\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\test\miniconda3\envs\data_analysis\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\test\miniconda3\envs\data_analysis\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\test\miniconda3\envs\data_analysis\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\test\miniconda3\envs\data_analysis\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [26]:
import numpy as np
import pandas as pd

In [27]:
d = {'a':11,'b':12,'c':13}
labels = ['a','b','c']
my_list = [22,45,66]
my_array = np.array([34,55,77])

In [28]:
pd.Series(my_array, index=labels)

a    34
b    55
c    77
dtype: int64

In [29]:
data_list = [
    ['john', 'peter', 'aman', 'lama'],
    [28,22,56,44],
    ["New York", "Paris", "Berlin", "London"],
    [55000, 65000, 45000, 66000]
]

In [30]:
df2 = pd.DataFrame(data_list, columns=["Name", "Age", "City", "Salary"], index=['a','b','c','d'])
df2

       Name    Age    City  Salary
a      john  peter    aman    lama
b        28     22      56      44
c  New York  Paris  Berlin  London
d     55000  65000   45000   66000

In [31]:
df2["Name"]

a        john
b          28
c    New York
d       55000
Name: Name, dtype: object

In [32]:
df2[["Name", "Age", "Salary"]]

       Name    Age  Salary
a      john  peter    lama
b        28     22      44
c  New York  Paris  London
d     55000  65000   66000

In [33]:
df2["Hobby"] = ["A", "B", "C", "D",]
df2

       Name    Age    City  Salary Hobby
a      john  peter    aman    lama     A
b        28     22      56      44     B
c  New York  Paris  Berlin  London     C
d     55000  65000   45000   66000     D

In [34]:
df2.drop("Hobby", axis = 1, inplace=True) # and you can write inplace=True which is gonna remove your data in your ram too

In [35]:
df2

       Name    Age    City  Salary
a      john  peter    aman    lama
b        28     22      56      44
c  New York  Paris  Berlin  London
d     55000  65000   45000   66000

In [36]:
df2.drop('a', axis = 0) # just change the axis to 0 and enter the index you want to remove

       Name    Age    City  Salary
b        28     22      56      44
c  New York  Paris  Berlin  London
d     55000  65000   45000   66000

In [37]:
df2.loc['b']

Name      28
Age       22
City      56
Salary    44
Name: b, dtype: object

In [38]:
data = {
    "Name": ["Rahul", "Priya", "Aman", "Sneha"],
    "Math": [85, 90, 75, 88],
    "Science": [80, 95, 82, 91]
}

df = pd.DataFrame(data)

In [41]:
df

    Name  Math  Science
0  Rahul    85       80
1  Priya    90       95
2   Aman    75       82
3  Sneha    88       85

In [44]:
df.loc[[0,1,3]][["Name","Math","Science"]]

    Name  Math  Science
0  Rahul    85       80
1  Priya    90       95
3  Sneha    88       85

In [45]:
data = {
    "Name": ["Rahul", "Priya", "Aman", "Sneha", "Ravi"],
    "Math": [85, 92, 76, 88, 65],
    "Science": [78, 89, 81, 95, 70]
}

df = pd.DataFrame(data)
df

    Name  Math  Science
0  Rahul    85       78
1  Priya    92       89
2   Aman    76       81
3  Sneha    88       95
4   Ravi    65       70

In [46]:
df["Math"] > 80

0     True
1     True
2    False
3     True
4    False
Name: Math, dtype: bool

In [49]:
df[df["Math"] > 80]

    Name  Math  Science
0  Rahul    85       78
1  Priya    92       89
3  Sneha    88       95

In [50]:
df[df["Name"] == "Rahul"]

    Name  Math  Science
0  Rahul    85       78

In [52]:
df[(df["Math"] > 80) | (df["Science"] > 80)]

    Name  Math  Science
0  Rahul    85       78
1  Priya    92       89
2   Aman    76       81
3  Sneha    88       95

In [68]:
df["Pass"] = df["Math"] >= 90

In [69]:
df

    Name  Math  Science   Pass
0  Rahul    85       78  False
1  Priya    92       89   True
2   Aman    76       81  False
3  Sneha    88       95  False
4   Ravi    65       70  False